### ISSUE TITLE
Classic Support

### ISSUE THREAD

**Issue by Dog** [ketho-wow/KethoCombatLog#1]
Hi,

I believe I have this addon mostly ported to classic. I have it loading with no errors, and events seem to be reporting without error so far.

However, I don't know enough about the addon yet to comprehensively test it. I'm a bit unsure how I should proceed - be it a PR, Fork, etc.

**Comment by Ketho** [comment]
Damn you must have yanked out quite a a bit of code to get it working. I'm also not sure, but I suggest you PR that to the [classic](https://github.com/ketho-wow/KethoCombatLog/tree/classic) branch. Then I'll see if I can just set that up separately for classic (vanilla?/tbc) releases.

As for testing, you'd have done more than me because I wouldn't even know the proper taunt/interrupt spell IDs.

**Comment by Dog** [comment]
I can tell there are a few things to still fix, but as long as I get through raid tonight without anything thrown I'll open the branch.

**Comment by Dog** [comment]
Opening the PR now. I fixed the bug that was bothering me most - the spell icons always defaulting to the question mark. There are still a few icons to fix in the interface.

https://user-images.githubusercontent.com/5172592/161874569-a81ed407-f328-4dbd-8782-5a92053f19e1.png

**Comment by Ketho** [comment]
This is not ideal, but setup classic packaging on a different repo since I'm too lazy to support classic properly
https://github.com/ketho-wow/KethoCombatLog-Classic
